image: nixos/19.09
packages:
  - nixpkgs.git
repositories:
  nixpkgs: https://nixos.org/channels/nixos-19.09
sources:
  - git@git.sr.ht:~madnat/haskell-tree-sitter
secrets:
  - ce4a1ba6-9c0a-43a7-96c9-e37c85e49742
  - 7a4d12b4-8878-4e27-83dd-cf6fe0045ffb
tasks:
  - setup-user: |
      git config --global user.name 'Sourcehut build'
      git config --global user.email 'build@sr.ht'
  - install-cachix: |
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use iohk
      cachix use famisoft
  - checkout: |
      cd haskell-tree-sitter
      git submodule sync --recursive
      git submodule update --init --recursive --force
  - build: |
      cd haskell-tree-sitter
      nix build -f release.nix | cachix push famisoft
  - mirror: |
      cd haskell-tree-sitter
      git remote add github https://github.com/jkopanski/haskell-tree-sitter.git
      git push -f github '+refs/remotes/origin/*:refs/heads/*' '+refs/tags/*:refs/tags/*'
